[toolchain]
package_manager = "yarn"

[features]
resolution = true
seeds = true
skip-lint = false

[programs.localnet]
sonicpact = "GrujK4NkA76V7BvkS66t1gAPXJKJgmF6dXoRGiq7CeoM"

[programs.devnet]
sonicpact = "GrujK4NkA76V7BvkS66t1gAPXJKJgmF6dXoRGiq7CeoM"

[programs.mainnet]
sonicpact = "GrujK4NkA76V7BvkS66t1gAPXJKJgmF6dXoRGiq7CeoM"

[provider]
cluster = "https://api.testnet.sonic.game"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
